process:
  daemon: true
  pid_dir: "tmp/tengined_pids"

tengined:
  load_path: "tengine_dsls/init.rb"
  status_dir: "tmp/tengined_status"
  activation_dir: "tmp/tengined_activations"
  heartbeat_period: 600
  confirmation_threshold: "warn"
event_queue:
  queue:
    name: tengine_event_queue2
